
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASSIGNDECREMENT ASSIGNINCREMENT ASSIGNMENT BREAK BREAK BREAK CASE CASE CASE CHOMP CHOMP CHOMP CLASS CLASS CLASS CLOSEDBRACKET COMMA DEF DEF DEF DIVISION DOT ELSE ELSE ELSE ELSIF ELSIF ELSIF END END END EQUALS FALSE FALSE FALSE FLOAT FOR FOR FOR GETS GETS GETS GREATEROREQUALS GREATERTHAN ID IF IF IF IN IN IN INTEGER LESSTHAN LPAREN MINUS MULTIPLICATION OPENBRACKET PLUS POWER PRINT PRINT PRINT PUTS PUTS PUTS RPAREN STRING THEN THEN THEN TO_F TO_F TO_F TO_I TO_I TO_I TRUE TRUE TRUE WHILE WHILE WHILEvariable : ID ASSIGNMENT varibles\n  varibles : FLOAT \n           | INTEGER\n           | ID\n  '
    
_lr_action_items = {'ID':([0,3,],[2,4,]),'$end':([1,4,5,6,7,],[0,-4,-1,-2,-3,]),'ASSIGNMENT':([2,],[3,]),'FLOAT':([3,],[6,]),'INTEGER':([3,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'variable':([0,],[1,]),'varibles':([3,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> variable","S'",1,None,None,None),
  ('variable -> ID ASSIGNMENT varibles','variable',3,'p_varibles','main.py',5),
  ('varibles -> FLOAT','varibles',1,'p_variablesP','main.py',9),
  ('varibles -> INTEGER','varibles',1,'p_variablesP','main.py',10),
  ('varibles -> ID','varibles',1,'p_variablesP','main.py',11),
]
